DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER`(
    `USER_ID`         VARCHAR(100) NOT NULL,
    `NAME`            VARCHAR(100) NOT NULL,
    `EMAIL`           VARCHAR(100) NOT NULL,
    `UPDATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`USER_ID`)
);

CREATE INDEX `IDX_USER_NAME` ON `USER` (`NAME`);
CREATE INDEX `IDX_USER_EMAIL` ON `USER` (`EMAIL`);


DROP TABLE IF EXISTS `RECORD`;

CREATE TABLE `RECORD`(
    `RECORD_ID`       BIGINT(20) NOT NULL AUTO_INCREMENT,
    `EXERCISE_NAME`   VARCHAR(100) NOT NULL,
    `RECORD_WEIGHT`   VARCHAR(100) NOT NULL,
    `USER_ID`         VARCHAR(100) NOT NULL,
    `UPDATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`RECORD_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES USER (`USER_ID`)
);

CREATE INDEX `IDX_RECORD_EXERCISE_NAME` ON `RECORD` (`EXERCISE_NAME`);
