DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER`(
    `USER_ID`         VARCHAR(100) NOT NULL,
    `NAME`            VARCHAR(100) NOT NULL,
    `EMAIL`           VARCHAR(100) NOT NULL,
    `UPDATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_TIME`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`USER_ID`)
);

CREATE INDEX `IDX_USER_NAME` ON `USER` (`NAME`);
CREATE INDEX `IDX_USER_EMAIL` ON `USER` (`EMAIL`);
